spring:  
  application:  
    name: TestSqlCombine  
  profiles:  
    active: dev  # 開発時はdev、本番時はprodなどに変更  

  sql:  
    init:  
      mode: never  
      schema-locations: classpath:schema.sql  
      data-locations: classpath:data.sql  

  jpa:  
    defer-datasource-initialization: true  
    database-platform: org.hibernate.dialect.MySQL8Dialect  
    hibernate:  
      ddl-auto: none

  datasource:  
    url: jdbc:mysql://localhost:3306/sql_combine_test  
    username: ${SPRING_DATASOURCE_USERNAME} 
    password: ${SPRING_DATASOURCE_PASSWORD}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html